[package]
name = "morse"
version = "0.1.0"
authors = ["Daniele D'Orazio <d.dorazio96@gmail.com>"]
edition = "2018"

[dependencies]
itertools = "0.8"
structopt = "0.3"

[dev-dependencies]
proptest = "0.9"
